//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARA.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutoRegistrationEntities : DbContext
    {
        public AutoRegistrationEntities()
            : base("name=AutoRegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Mapping> Mappings { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<SKU> SKUs { get; set; }
        public virtual DbSet<Threshold> Thresholds { get; set; }
    }
}
