//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int CourseID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
    }
}
