//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int EnrollmentID { get; set; }
        public int MappingID { get; set; }
        public int iMISID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public System.DateTime EnrolledOn { get; set; }
    
        public virtual Mapping Mapping { get; set; }
    }
}
