//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapping
    {
        public Mapping()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public int MappingID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> SchoologyCourseID { get; set; }
        public Nullable<int> SchoologyGroupID { get; set; }
        public string CECityActivityID { get; set; }
        public bool Active { get; set; }
        public int MaxEnrollment { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual Section Section { get; set; }
    }
}
