//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Mappings = new HashSet<Mapping>();
            this.Notifications = new HashSet<Notification>();
            this.SKUs = new HashSet<SKU>();
        }
    
        public int SectionID { get; set; }
        public int CourseID { get; set; }
        public Nullable<System.DateTime> RegistrationOpen { get; set; }
        public Nullable<System.DateTime> RegistrationCloses { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Mapping> Mappings { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<SKU> SKUs { get; set; }
    }
}
