//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARA.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Threshold
    {
        public Threshold()
        {
            this.Notifications = new HashSet<Notification>();
        }
    
        public int ThresholdID { get; set; }
        public int ThresholdLevel { get; set; }
        public string Recipients { get; set; }
        public string EmailBody { get; set; }
    
        public virtual ICollection<Notification> Notifications { get; set; }
    }
}
